# Use an official node image as the base
FROM node:16-alpine

# Set the working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy the rest of the application
COPY . .

# Build the application
RUN npm run build

# Serve the application using a minimal HTTP server
RUN npm install -g serve

# Expose the port the app runs on
EXPOSE 5001

# Start the application
CMD ["serve", "-s", "build", "-l", "5001"]
