services:
  db:
    image: postgres:latest
    restart: always
    environment:
      POSTGRES_DB: shopping_list
      POSTGRES_USER: shopping_user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
      - pgdata:/var/lib/postgresql/data

  backend:
    build:
      context: ./backend
    restart: always
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      DB_HOST: db
      DB_PORT: 5432
      DB_USER: shopping_user
      DB_PASSWORD: password
      DB_NAME: shopping_list

  frontend:
    build:
      context: ./frontend
    ports:
      - "5001:5001"
    depends_on:
      - backend
      - db

volumes:
  pgdata:
