version: '3.8'

services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "5000:5000"
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
    ports:
      - "8080:8080"
    depends_on:
      - db
    environment:
      - DB_HOST=db
      - DB_PORT=5432
      - DB_USER=shopping_user
      - DB_PASSWORD=password
      - DB_NAME=shopping_list

  db:
    build:
      context: ./database
    environment:
      - POSTGRES_DB=shopping_list
      - POSTGRES_USER=shopping_user
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql

volumes:
  db-data:
