# Use an official golang image as the base
FROM golang:1.22.5-alpine

# Set environment variables
ENV GO111MODULE=on

# Set the working directory
WORKDIR /app

# Copy go.mod and go.sum files
COPY go.mod go.sum ./

# Download all dependencies
RUN go mod download

# Copy the entire project
COPY . .

# Command to run all tests
RUN go test ./...

# Build the Go application
RUN go build -o ./shoppinglist-backend ./cmd/shoppinglist-api

# Expose the port the app runs on
EXPOSE 8080

# Command to run the application
CMD ["./shoppinglist-backend"]
