# Use the official PostgreSQL image from the Docker Hub
FROM postgres:latest

# Set environment variables for PostgreSQL
ENV POSTGRES_DB=shopping_list
ENV POSTGRES_USER=shopping_user
ENV POSTGRES_PASSWORD=password

# Copy initialization scripts
COPY init-db.sh /docker-entrypoint-initdb.d/
COPY create-tables.sql /docker-entrypoint-initdb.d/

# Expose the PostgreSQL port
EXPOSE 5432
